### ISSUE TITLE
Local dev environment

### ISSUE THREAD

**Issue by Razzwan** [ston-fi/tonlib-rs#57]
Does it possible to use local dev env with this lib instead of testnet? Such way it would be possible to use it for tests, which is better then TypeScript

**Comment by Sild** [comment]
Frankly speaking I didn't get you question, but my guess - not it's not

This is a client for ton blockchain, not server-node. It's impossible to send request to the client

Sure you can write your own wrapper to make it works as a server, but response time will be the same as for testnet (because client always use lite-nodes to get any data)
